name: Process KiCad

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'kicad/**'
      - '.github/workflows/process-kicad.yml'

concurrency:
  group: Compile
  cancel-in-progress: true

jobs:
  ProcessKicad:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: pull kicad docker
        run: |
          git config --global user.name 'gbg-with-joysticks'
          git config --global user.email 'gbg-with-joysticks@users.noreply.github.com'
          git pull

          docker pull kicad/kicad:10.0-full
      - name: process kicad
        run: |
          docker run --rm --user root --mount type=bind,source=${{ github.workspace }},target=/workspace kicad/kicad:10.0-full /bin/bash -c "
            kicad-cli sch export pdf --no-background-color --output '/workspace/schematic.pdf' /workspace/kicad/gbg-pcb.kicad_sch
            kicad-cli sch export bom /workspace/kicad/gbg-pcb.kicad_sch --output /workspace/PCB_production/BOM.csv --fields 'Reference,Value,Footprint,Manufacturer_Name,Manufacturer_Part_Number,digikey_part_number,mount_type,\${QUANTITY}' --group-by Manufacturer_Part_Number --exclude-dnp
            kicad-cli sch export bom /workspace/kicad/gbg-pcb.kicad_sch --output /workspace/PCB_production/BOM-with-DNP.csv --fields 'Reference,Value,Footprint,Manufacturer_Name,Manufacturer_Part_Number,digikey_part_number,mount_type,\${QUANTITY}' --group-by Manufacturer_Part_Number
            kicad-cli pcb export gerbers --layers F.Cu,B.Cu,F.Paste,B.Paste,F.Silkscreen,B.Silkscreen,F.Mask,B.Mask,Edge.Cuts /workspace/kicad/gbg-pcb.kicad_pcb --output /workspace/PCB_production/gerbers
            kicad-cli pcb export drill /workspace/kicad/gbg-pcb.kicad_pcb --output /workspace/PCB_production/gerbers
            kicad-cli pcb export pos --output '/workspace/PCB_production/position.csv' --smd-only /workspace/kicad/gbg-pcb.kicad_pcb
            kicad-cli pcb export dxf --output '/workspace/PCB_production/F_SolderPasteMask.dxf' --layers F.Paste --mode-single --output-units mm --drill-shape-opt 0 --common-layers '' /workspace/kicad/gbg-pcb.kicad_pcb
          "
          cd ${{ github.workspace }}/PCB_production
          cd gerbers
          sudo rm gbg-pcb-job.gbrjob
          cd ..
          zip -r gerbers.zip ./gerbers
          sudo rm -rf ${{ github.workspace }}/PCB_production/gerbers
            
          git add .
          git commit . -m "BOT process kicad" --allow-empty
          git push

      - name: process kicad
        run: |
          docker run --rm --user root --mount type=bind,source=${{ github.workspace }},target=/workspace kicad/kicad:10.0-full /bin/bash -c "
            kicad-cli pcb render --output '/workspace/renders/top.jpg' --quality high --rotate '0,0,0' --width 1000 --height 1000 /workspace/kicad/gbg-pcb.kicad_pcb
            kicad-cli pcb render --output '/workspace/renders/back.jpg' --quality high --rotate '180,0,180' --width 1000 --height 1000 /workspace/kicad/gbg-pcb.kicad_pcb
            kicad-cli pcb render --output '/workspace/renders/perspective1.jpg' --quality high --perspective --zoom 0.65 --rotate '315,0,45' --width 1000 --height 1000 /workspace/kicad/gbg-pcb.kicad_pcb
            kicad-cli pcb render --output '/workspace/renders/perspective2.jpg' --quality high --perspective --zoom 0.65 --rotate '315,0,315' --width 1000 --height 1000 /workspace/kicad/gbg-pcb.kicad_pcb
            kicad-cli pcb export stl --output /workspace/renders/gbg-pcb.stl /workspace/kicad/gbg-pcb.kicad_pcb
            kicad-cli pcb export step --output /workspace/renders/gbg-pcb.step /workspace/kicad/gbg-pcb.kicad_pcb
          "

          git add .
          git commit . -m "BOT render images" --allow-empty
          git push
      - name: Run iBOM Generator
        run: |
          docker run --rm --user root --mount type=bind,source=${{ github.workspace }},target=/workspace \
                kicad/kicad:10.0-full /bin/bash -c "
                    apt-get update &&
                    apt-get install -y python3-venv python3-pip &&
                    python3 -m venv --system-site-packages /tmp/ihb-venv &&
                    source /tmp/ihb-venv/bin/activate &&
                    pip install --no-deps InteractiveHtmlBom==2.11.1 &&
                    export INTERACTIVE_HTML_BOM_NO_DISPLAY=1 &&
                    generate_interactive_bom --dest-dir /workspace/docs/ibom --include-tracks --include-nets --no-browser --mark-when-checked Placed \
                    --show-fields 'Value,Footprint,Datasheet,digikey_part_number,Manufacturer_Part_Number,kicad_dnp,mount_type' \
                    --group-fields 'Value,Footprint,digikey_part_number,kicad_dnp,mount_type' \
                    /workspace/kicad/gbg-pcb.kicad_pcb
                "
                git add .
                git commit -m "BOT Update interactive BOM"
                git push
